# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_base.ipynb.

# %% auto 0
__all__ = ['return_multiple', 'return_subtraction', 'foo']

# %% ../nbs/00_base.ipynb 2
def return_multiple(a,b):
    "Resturn a*b"
    
    return a*b

def return_subtraction(a,b):
    "Return a-b"
    return a-b


# %% ../nbs/00_base.ipynb 10
def foo(): pass
